# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Install vagrant-disksize to allow resizing the vagrant box disk.
  unless Vagrant.has_plugin?("vagrant-disksize")
    raise Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
  end

  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = '40GB'

  # Mount given path in /home/vagrant/dev
  # config.vm.synced_folder "C:\\Path\\To\\Some\\Folder", "/home/vagrant/dev"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.provider "virtualbox" do |vb|
	  vb.name = "ubuntu-xenial"    
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "\n----- Upgrade OS and cleanup ------\n"
    apt-get update
    apt-get -y upgrade
    apt-get -y install --install-recommends linux-generic
    apt-get -y autoremove
    
    echo "\n----- Install Docker ------\n"
    wget -qO- https://get.docker.com/ | sh
    usermod -aG docker vagrant

    echo "\n----- Install kubectl ------\n"
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin/kubectl

    echo "\n----- Install k3d ------\n"
    wget -q -O - https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash
    usermod -aG docker vagrant

    echo "\n----- Install git ------\n"
    apt-get -y install git

    echo "\n----- Install Azure CLI ------\n"
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    echo "\n----- Install Skaffold ------\n"
    curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
    chmod +x ./skaffold
    mv ./skaffold /usr/local/bin

    echo "\n----- Install Helm ------\n"
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

  SHELL
end